version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017 
  
  tictactoeapi:
    image: ${DOCKER_REGISTRY-}tictactoeapi
    build:
      context: .
      dockerfile: TicTacToeAPI/Dockerfile    
    depends_on:
        - mongo